algoritmo "exponeciação"
// Função : Faça um programa que receba dois números, calcule e mostre um número elevado ao outro
// Autor : Kelly Araújo
// Data : 04/03/2025
// Seção de Declarações 
var
n_1,n_2,resultado_f:real
inicio
// Seção de Comandos
Escreval("Informe o numero base")
Leia(n_1)
Escreval("Informe o numero expoente")
Leia(n_2)
resultado_f <- n_1^n_2
Escreval("o resultado é",resultado_f)
fimalgoritmo
