algoritmo "conversao de temperatura"
// Função : Faça um programa que recebe a medida de temperatura em Celsius, calcula e mostra a conversão desta medida em Fahrenheit. Sabe-se que F= 1,8*C +32.
// Autor :Kelly Araújo
 // Data : 05/03/2025
// Seção de Declarações
var
 medida_c,medida_F:real
 inicio
// Seção de Comandos
Escreval("Qual a medida de temperatura em Celsius")
Leia(medida_c)
medida_F<-((1.8*medida_c)+32 )
Escreval("A medida em Fahrenheit é",medida_F,"F")
fimalgoritmo

