algoritmo "Nome e idade"
// Função : a) Uma saudação com o nome que foi digitado b) Informar a idade da pessoa
// Autor :Kelly Araújo
// Data : 28/02/2025
// Seção de Declarações 
var
nome_pes:caractere
idade_pes,ano_nasc:inteiro
inicio
// Seção de Comandos 
Escreval("Informe é o seu nome")
Leia(nome_pes)
Escreval("Informe o seu ano de nascimento")
Leia(ano_nasc)
idade_pes<-(2025-ano_nasc)
Escreval("Olá", nome_pes , ",você tem" , idade_pes , "anos")
fimalgoritmo
