algoritmo "antecessor  e sucessor "
// Função : leia um número inteiro, calcule e mostre o seu antecessor e o seu sucessor.
// Autor : Kelly Araújo
// Data : 28/02/2025
// Seção de Declarações 
var
num_I:inteiro
inicio
// Seção de Comandos 
Escreval("Informe um número")
Leia(num_I)
Escreval("o antecessor desse número é o número ", num_I-1 ,"e o sucessor desse número é o número ",num_I+1)
fimalgoritmo
