algoritmo "triângulo equilátero"
// Função : calcule e mostre a área de um triângulo equilátero.
// Autor : Kelly Araújo
// Data : 28/02/2025
// Seção de Declarações 
var
base_t,altura_t,area_t:real
inicio
// Seção de Comandos
Escreval("Informe o valor da base do triângulo")
Leia(base_t)
Escreval("Informe o valor da altura do triângulo")
Leia(altura_t)
area_t<-(base_t*altura_t)/2
Escreval("A área do triângulo equilátero é",area_t)
fimalgoritmo
